version: '3'

services:
  db:
    image: mysql  
    container_name: mysql
    restart: always
    volumes:
      # 이 경로에 mysql-data폴더 생성 필요
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=rootdb
    ports:
      - "3309:3306"

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      # 이 경로에 redis-data폴더 생성 필요
      - ./redis-data:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      # 이 경로에 postgres-data폴더 생성 필요
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
